In [ ]:
gutenberg_texts = nltk.corpus.gutenberg.fileids()
print(gutenberg_texts)

['austen-emma.txt', 'austen-persuasion.txt', 'austen-sense.txt', 'bible-kjv.txt', 'blake-poems.txt', 'bryant-stories.txt', 'burgess-busterbrown.txt', 'carroll-alice.txt', 'chesterton-ball.txt', 'chesterton-brown.txt', 'chesterton-thursday.txt', 'edgeworth-parents.txt', 'melville-moby_dick.txt', 'milton-paradise.txt', 'shakespeare-caesar.txt', 'shakespeare-hamlet.txt', 'shakespeare-macbeth.txt', 'whitman-leaves.txt']


In [ ]:
from nltk import word_tokenize, pos_tag
sentence = "Mary is driving a big car"
tokens = word_tokenize(sentence)
pos_tags = pos_tag(tokens)
for word, tag in pos_tags:
  print(f"{word}: {tag}")

Mary: NNP
is: VBZ
driving: VBG
a: DT
big: JJ
car: NN


In [ ]:
#sent = "Mary is driving a big car."
sent = "Apple is a fruit and Apple is a Company's name"
import nltk
import nltk.corpus
from nltk.tokenize import word_tokenize
from nltk.tokenize import RegexpTokenizer
nltk.download('punkt')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [ ]:
sent_tokens = word_tokenize(sent)

In [ ]:
print(sent_tokens)

['Apple', 'is', 'a', 'fruit', 'and', 'Apple', 'is', 'a', 'Company', "'s", 'name']


In [ ]:
for token in sent_tokens:
  print(nltk.pos_tag([token]))

NE_tags = nltk.pos_tag([token])

[('Apple', 'NNP')]
[('is', 'VBZ')]
[('a', 'DT')]
[('fruit', 'NN')]
[('and', 'CC')]
[('Apple', 'NNP')]
[('is', 'VBZ')]
[('a', 'DT')]
[('Company', 'NN')]
[("'s", 'POS')]
[('name', 'NN')]


In [ ]:
from nltk import ne_chunk
nltk.download('maxent_ne_chunker')
nltk.download('words')
NE_NER = ne_chunk(NE_tags)

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.


In [ ]:
print(NE_NER)

(S name/NN)


In [ ]:
# prompt: write python word to remove stop words in nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
sentence = "Mary is driving a big car."
words = word_tokenize(sentence)
filtered_words = [word for word in words if word.lower() not in stop_words]
print(filtered_words)


['Mary', 'driving', 'big', 'car', '.']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
# prompt: remove the stop words

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
sentence = "Mary is driving a big car."
words = word_tokenize(sentence)
filtered_words = [word for word in words if word.lower() not in stop_words]
print(filtered_words)


['Mary', 'driving', 'big', 'car', '.']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
documents = [
    "This is the first document.",
    "This document is the second document.",
    "And this is the third one.",
    "Is this the first document?",
]

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# Download stopwords and punkt tokenizer if not already downloaded
nltk.download('stopwords')
nltk.download('punkt')

# Sample documents
documents = [
    "This is the first document.",
    "This document is the second document.",
    "And this is the third one.",
    "Is this the first document?",
]

# Tokenized documents list
tokenized_documents = []

# Remove stopwords
stop_words = set(stopwords.words('english'))

# Iterate through documents
for doc in documents:
    # Tokenize document
    words = word_tokenize(doc)

    # Convert tokens to lowercase and remove stopwords using for loop
    filtered_words = []
    for word in words:
        if word.lower() not in stop_words:
            filtered_words.append(word.lower())

    # Add filtered tokens to tokenized documents list
    tokenized_documents.append(filtered_words)

# Print tokenized documents
for i, doc in enumerate(tokenized_documents):
    print(f"Document {i + 1}: {doc}")

Document 1: ['first', 'document', '.']
Document 2: ['document', 'second', 'document', '.']
Document 3: ['third', 'one', '.']
Document 4: ['first', 'document', '?']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
# create a list of the unique words in the documents
# Create a vocabulary (list of unique words)
filtered_documents = [[word for word in doc if word not in stop_words] for doc in tokenized_documents]
vocabulary = list(set(word for doc in filtered_documents for word in doc))
print(vocabulary)

['.', 'third', 'one', 'second', '?', 'document', 'first']


In [ ]:
# tokenized , removed the stop words, unique words
from collections import Counter
import numpy as np
# Compute Bag of Words representation
bow_matrix = np.zeros((len(filtered_documents), len(vocabulary)))
for i, doc in enumerate(filtered_documents):
    word_counts = Counter(doc)
    for word, count in word_counts.items():
        word_index = vocabulary.index(word)
        bow_matrix[i, word_index] = count

In [ ]:
# Display Bag of Words matrix
print("Vocabulary:", vocabulary)
print("Bag of Words Matrix:")
print(bow_matrix)

Vocabulary: ['.', 'third', 'one', 'second', '?', 'document', 'first']
Bag of Words Matrix:
[[1. 0. 0. 0. 0. 1. 1.]
 [1. 0. 0. 1. 0. 2. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1.]]


In [ ]:
# scikit learn


from sklearn.feature_extraction.text import CountVectorizer

# Sample documents
documents = [
    "The movie was good and we really like it",
    "The movie was good but the ending was boring ",
    "we did not like the movie as it was too lengthy",
]

# Create CountVectorizer object
vectorizer = CountVectorizer(stop_words= 'english', lowercase=True)

# Fit and transform the documents
bow_matrix = vectorizer.fit_transform(documents)

# Get the vocabulary
vocabulary = vectorizer.get_feature_names_out()

# Convert bag of words matrix to dense array for easy printing
bow_matrix_dense = bow_matrix.toarray()

# Display Bag of Words matrix
print("Vocabulary:", vocabulary)
print("Bag of Words Matrix:")
print(bow_matrix_dense)

Vocabulary: ['boring' 'did' 'ending' 'good' 'lengthy' 'like' 'movie' 'really']
Bag of Words Matrix:
[[0 0 0 1 0 1 1 1]
 [1 0 1 1 0 0 1 0]
 [0 1 0 0 1 1 1 0]]


In [ ]:
TfidfVectorizer()

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
# Sample documents
documents = [
    "The movie was good and we really like it",
    "The movie was good but the ending was boring ",
    "we did not like the movie as it was too lengthy",
]
# Create TfidfVectorizer object
tfidf_vectorizer = TfidfVectorizer(stop_words='english', lowercase=True)
# Fit and transform the documents
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)
# Get the vocabulary
vocabulary = tfidf_vectorizer.get_feature_names_out()
# Convert TF-IDF matrix to dense array for easy printing
tfidf_matrix_dense = tfidf_matrix.toarray()
# Display TF-IDF matrix
print("Vocabulary:", vocabulary)
print("TF-IDF Matrix:")
print(tfidf_matrix_dense)

Vocabulary: ['boring' 'did' 'ending' 'good' 'lengthy' 'like' 'movie' 'really']
TF-IDF Matrix:
[[0.         0.         0.         0.4804584  0.         0.4804584
  0.37311881 0.63174505]
 [0.5844829  0.         0.5844829  0.44451431 0.         0.
  0.34520502 0.        ]
 [0.         0.5844829  0.         0.         0.5844829  0.44451431
  0.34520502 0.        ]]
